### ISSUE TITLE
Can you help me please to use /dev/i2c-0 instead i2c-1?

### ISSUE THREAD

**Issue by FPSychotic** [tleyden/donkey-ros#2]
I found these lines related but I cannot understand what I need to do. as I dont know programming, can you help me please?
`/**
 \private method to initialize private internal data structures at startup

@param devicename a string value indicating the linux I2C device

Example _init ("/dev/i2c-1");  // default I2C device on RPi2 and RPi3 = "/dev/i2c-1"
 */
static void _init (const char* filename)
{
    int res;
    char mode1res;
    int i;

    /* initialize all of the global data objects */`

**Comment by tleyden** [comment]
I think you might want to ask on https://gitlab.com/bradanlane/ros-i2cpwmboard instead.  Also, can you point me to that code that you referenced?

**Comment by FPSychotic** [comment]
sorry by ask here, It looks the project is abandoned as a question similar to this wasn't answered in long time, the emails doesn't work either. Just I thought try here, maybe is a easy thing,but not for me.
thanks anyway, and sorry if I asked in wrong place.
if you want take a look the file is the one in the source folder
https://gitlab.com/bradanlane/ros-i2cpwmboard/-/blob/master/src/i2cpwm_controller.cpp
thanks and take care!!
